FROM amazoncorretto:11-al2-full

# Setup Environment
ENV NECESSE_PORT 14159
ENV NECESSE_SLOTS 10
ENV NECESSE_PASSWORD ''
ENV NECESSE_PAUSE_WHEN_EMPTY false
ENV NECESSE_GIVE_CLIENTS_POWER true
ENV NECESSE_LOGGING true
ENV NECESSE_LANGUAGE en
ENV NECESSE_ZIP_SAVES false
ENV NECESSE_MOTD Powered by Docker

ENV NECESSE_WORLD_NAME world
ENV NECESSE_ALLOW_CHEATS false
ENV NECESSE_DIFFICULTY NORMAL
ENV NECESSE_DEATH_PENTALTY DROP_MATS
ENV NECESSE_RAID_FREQUENCY OCCASIONALLY
ENV NECESSE_PLAYER_HUNGER true
ENV NECESSE_DISABLE_MOB_SPAWNS false
ENV NECESSE_FORCED_PVP false
ENV NECESSE_UNLOAD_SETTLEMENTS false
ENV NECESSE_MAX_SETTLEMENTS_PER_PLAYER -1
ENV NECESSE_DAY_TIME_MOD 1.0
ENV NECESSE_NIGHT_TIME_MOD 1.0

# Set working directory
WORKDIR /app

# Copy server files
COPY ./necesse-server /app
COPY ./start.sh /app
COPY ./create-config.sh /app

# Fix permissions
RUN chmod a+x /app/StartServer-nogui.sh
RUN chmod a+x /app/jre/bin/java

# Setup startup command
CMD "/app/start.sh"
